### ISSUE TITLE
ICrashing with slice bounds out of range

### ISSUE THREAD

**Issue by cloudkucooland** [Sorrow446/go-mp4tag#10]
I'm able to consistently get a crash when writing tags on ALAC files. Any suggestions?

scot@covert:/home/scot/SmartAlac % go run cmd/curate/main.go -d "/home/data/alac/Police, The/" 
2023/12/30 21:03:26 /home/data/alac/Police, The/Every Breath You Take [1983,12″ Vinyl,US,A&M Records,SP-17230]/1-01 Every Breath You Take.m4a
AlbumSort			 "" != "Every Breath You Take"
AlbumArtistSort			 "" != "Police, The"
Custom["Country"]			 (missing) != "United States"
Custom["BARCODE"]			 (missing) != ""
Date			 "" != "1983"
panic: runtime error: slice bounds out of range [:169120469] with capacity 4194304

goroutine 1 [running]:
github.com/Sorrow446/go-mp4tag.MP4.readToOffset({0xc0000a4148?, {0xc0000e2780?, 0x41?}, 0x34?}, 0x48463e?, 0x51492d5)
	/home/scot/go/pkg/mod/github.com/!sorrow446/go-mp4tag@v0.0.0-20231216231332-6bc94dacffd5/write.go:355 +0x17f
github.com/Sorrow446/go-mp4tag.MP4.writeTags({0xc0000a4148?, {0xc0000e2780?, 0x0?}, 0x0?}, {{0xc0004b3800?, 0x0?, 0x0?}}, 0xc000002480, {0xc000024580, 0x35})
	/home/scot/go/pkg/mod/github.com/!sorrow446/go-mp4tag@v0.0.0-20231216231332-6bc94dacffd5/write.go:802 +0x1e5
github.com/Sorrow446/go-mp4tag.(*MP4).actualWrite(0xc0000ad040, 0xc000179410?, {0xc0001b9888?, 0x0, 0xc0000a6300?})
	/home/scot/go/pkg/mod/github.com/!sorrow446/go-mp4tag@v0.0.0-20231216231332-6bc94dacffd5/write.go:1055 +0x2bb
github.com/Sorrow446/go-mp4tag.(*MP4).Write(...)
	/home/scot/go/pkg/mod/github.com/!sorrow446/go-mp4tag@v0.0.0-20231216231332-6bc94dacffd5/mp4tag.go:23
github.com/cloudkucooland/SmartAlac.wdf({0xc000082240, 0x5f}, {0x8acab8?, 0xc0000de800?}, {0xc00011f9c8?, 0x4d0d9d?})
	/home/scot/SmartAlac/filetree.go:62 +0x1f9
io/fs.walkDir({0x8aabe0, 0xc000093cb0}, {0xc000082240, 0x5f}, {0x8acab8, 0xc0000de800}, 0x848f18)
	/usr/lib/golang/src/io/fs/walk.go:73 +0x78
io/fs.walkDir({0x8aabe0, 0xc000093cb0}, {0xc0000d6580, 0x40}, {0x8acab8, 0xc0000de700}, 0x848f18)
	/usr/lib/golang/src/io/fs/walk.go:95 +0x2e6
io/fs.walkDir({0x8aabe0, 0xc000093cb0}, {0x8a6690, 0x1}, {0x8aca10, 0xc000093cc0}, 0x848f18)
	/usr/lib/golang/src/io/fs/walk.go:95 +0x2e6
io/fs.WalkDir({0x8aabe0, 0xc000093cb0}, {0x8a6690, 0x1}, 0x848f18)
	/usr/lib/golang/src/io/fs/walk.go:122 +0xde
github.com/cloudkucooland/SmartAlac.WalkTree(...)
	/home/scot/SmartAlac/filetree.go:24
main.main.func1(0xc000164160?)
	/home/scot/SmartAlac/cmd/curate/main.go:41 +0x98
github.com/urfave/cli/v2.(*Command).Run(0xc000164160, 0xc0000de4c0, {0xc000094150, 0x3, 0x3})
	/home/scot/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0xa3c
github.com/urfave/cli/v2.(*App).RunContext(0xc000162000, {0x8ac738?, 0xc0000a2010}, {0xc000094150, 0x3, 0x3})
	/home/scot/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x63a
github.com/urfave/cli/v2.(*App).Run(...)
	/home/scot/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/home/scot/SmartAlac/cmd/curate/main.go:48 +0x3e9

**Comment by cloudkucooland** [comment]
Ah, I see, the bufSize you use in write.go is too tiny for huge high-res ALAC files. Can you crank that way up?

**Comment by Sorrow446** [comment]
Yep. Could you send me the ALAC and your code over Discord?
