### ISSUE TITLE
Add a command-line tool

### ISSUE THREAD

**Issue by prologic** [Sorrow446/go-mp4tag#3]
Add a (for example) `./cmd/mp4tag/main.go` command-line implementation that uses this library so it can be used as both a library and tool

**Comment by Sorrow446** [comment]
Hello, I already have this planned :p. If you'd like to make a start on this yourself, please use https://github.com/alexflint/go-arg.
I'll start work on it tomorrow if you haven't already.

**Comment by prologic** [comment]
Ahh I would have used https://github.com/spf13/pflag myself 😅 so I'll let you at it! 😂 I'm not familiar with go-arg sorry!

**Comment by Sorrow446** [comment]
All done.
