### ISSUE TITLE
Please add a license :-)

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Sorrow446/go-mp4tag#6]
Hi, sorry to bother you! I've stumbled across your cool-looking library, but, before I even give it a try, I'd like to know under which license you're releasing it...

You explicitly mention that you rely heavily on abema/go-mp4 (who doesn't? 😸 ), which is MIT-licensed (my favourite license, BTW), which, in turn, means that you can basically release go-mp4tag under whatever license you like most.

So, which one will it be? 😸 

(Note: by setting a 'proper' license, you will even be able to get all the documentation auto-extracted and displayed under pkg.go.dev; without a license, Google won't touch your code. Remember that "no license" does **not** mean "public domain" but rather "fully copyrighted" — even if its source code is open & public!)

**Comment by Sorrow446** [comment]
Done.
