### ISSUE TITLE
Deprecated usage of io/ioutil package

### ISSUE THREAD

**Issue by GwynethLlewelyn** [Sorrow446/go-mp4tag#7]
Hi again,

I've noticed that you use `ioutil.Readfile()` to load external files — such as to load image data for album covers. The whole `io/ioutil` package is considered to be deprecated, since its functionality can be replicated in a much better way by other Go packages from the standard library.

More specifically, consider replacing `ioutil.Readfile()` with `os.ReadFile()`, which is pretty much a drop-in replacement, and you're using the `os` package anyway — so, saving you a few bytes from a package that you shouldn't use :-)

This is obviously low priority, I'm assuming that Google sticks to its policy of never breaking things under Go 1.X, and thus continuing to support deprecated packages for quite a while longer (we might _never_ see a Go 2.0 version anyway!). Still, sticking to non-deprecated packages & functions makes linters and code inspection tools happy :) and are definitely recommended.

**Comment by Sorrow446** [comment]
I haven't used Go in a bit (it's still my main). I'm considering porting my Crystal MP4 tag lib https://github.com/Sorrow446/mp4tag.cr. It doesn't rely on any MP4 library.
